version: "3.5"

services:
  dev:
    container_name: hfcp-rack-frontend-dev
    build:
      context: .
      dockerfile: local.Dockerfile
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  test:
    container_name: react-app-test
    build:
      context: .
      dockerfile: local.Dockerfile
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - CI=true
    command: npm run test

  prod:
    container_name: react-app-prod
    build:
      context: .
      dockerfile: production.Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
